export const logs = [
  {
    isBreakthrough: false,
    date: '2025-06-18',
    v: '1.4.3',
    description: `- 新增暗黑模式`,
  },
  {
    isBreakthrough: false,
    date: '2025-06-10',
    v: '1.4.2',
    description: `- 改变项目异常的体现`,
  },
  {
    isBreakthrough: false,
    date: '2025-06-07',
    v: '1.4.1',
    description: `- 允许替换背景图片`,
  },
  {
    isBreakthrough: true,
    date: '2025-06-06',
    v: '1.4.0',
    description: `- 带来全新 macOS 风格输出`,
  },
  {
    isBreakthrough: false,
    date: '2025-05-15',
    v: '1.3.2',
    description: `- 支持 Mermaid 和 KaTex 渲染`,
  },
  {
    isBreakthrough: false,
    date: '2025-05-13',
    v: '1.3.1',
    description: `- 允许用户自定义页脚图片`,
  },
  {
    isBreakthrough: true,
    date: '2025-05-09',
    v: '1.3.0',
    description: `- 日报增加自定义页脚，“项目”新增“剩余日”维度`,
  },
  {
    isBreakthrough: false,
    date: '2025-05-08',
    v: '1.2.3',
    description: `- 新增“彩蛋”，快来寻找吧！`,
  },
  {
    isBreakthrough: false,
    date: '2025-05-08',
    v: '1.2.2',
    description: `- 使用路由代替组件插槽`,
  },
  {
    isBreakthrough: false,
    date: '2025-05-08',
    v: '1.2.1',
    description: `- 优化了界面布局`,
  },
  {
    isBreakthrough: true,
    date: '2025-05-08',
    v: '1.2.0',
    description: `- 使用 Vuetify 重构项目`,
  },
  {
    isBreakthrough: true,
    date: '2025-05-07',
    v: '1.1.0',
    description: `- 新增主题系统`,
  },
  {
    isBreakthrough: false,
    date: '2025-04-09',
    v: '1.0.8',
    description: `- 支持 TLS 加密通讯`,
  },
  {
    isBreakthrough: false,
    date: '2025-04-09',
    v: '1.0.7',
    description: `- 修改不安全上下文提醒的出现方式`,
  },
  {
    isBreakthrough: false,
    date: '2025-04-07',
    v: '1.0.6',
    description: `- 支持在事件中直接编写 Markdown`,
  },
  {
    isBreakthrough: false,
    date: '2025-04-07',
    v: '1.0.5',
    description: `- 允许用户导出日报为 JSON、导入 JSON 日报`,
  },
  {
    isBreakthrough: false,
    date: '2025-04-01',
    v: '1.0.4',
    description: `- 支持在事件中直接编写 Markdown`,
  },
  {
    isBreakthrough: false,
    date: '2025-04-01',
    v: '1.0.3',
    description: `- 支持直接在应用内编辑日报`,
  },
  {
    isBreakthrough: false,
    date: '2025-03-28',
    v: '1.0.2',
    description: `- 支持将日报图片复制到剪切板`,
  },
  {
    isBreakthrough: false,
    date: '2025-03-28',
    v: '1.0.1',
    description: `- 支持保存日报为图片`,
  },
  {
    isBreakthrough: true,
    date: '2025-03-12',
    v: '1.0.0',
    description: `- 正式版发布，欢迎使用！`,
  },
  {
    isBreakthrough: false,
    date: '2025-03-12',
    v: 'INDEV-0.0.1',
    description: `- 现在“项目/事件”可以被手动高亮了`,
  },
  {
    isBreakthrough: true,
    date: '2025-03-05',
    v: 'INDEV-0.0.0',
    description: `- 首次带来工作日报美化器，欢迎体验！`,
  },
]
